### ISSUE TITLE
where is the Proximity.csv?

### ISSUE THREAD

**Issue by WzkPioneer** [uoguelph-mlrg/LDG#1]
![9B5A{WR~YY(RZGR3W2@2`V6](https://user-images.githubusercontent.com/41323973/68857279-6fd69000-071d-11ea-9522-475291856264.png)

**Comment by bknyaz** [comment]
Thanks for reporting. I uploaded it here https://github.com/uoguelph-mlrg/LDG/blob/master/SocialEvolution/Proximity.csv.bz2. It was initially skipped by github, because it was too big.
It needs to be unzipped before using. 
A also uploaded the entire dataset to https://github.com/uoguelph-mlrg/LDG/blob/master/SocialEvolution.zip.

**Comment by WzkPioneer** [comment]
By the way, I am going to do Dyrep's experiment. Does your LDG project have an experiment to achieve it?
（I am a Student from China,and my group is working on a paper on Dyrep.So I want to know how your progress in implementing this experiment is going. ）








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Boris Knyazev"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 晚上10:18
收件人:&nbsp;"uoguelph-mlrg/LDG"<LDG@noreply.github.com&gt;;
抄送:&nbsp;"Neverland"<2235331207@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [uoguelph-mlrg/LDG] where is the Proximity.csv? (#1)




Thanks for reporting. I uploaded it here https://github.com/uoguelph-mlrg/LDG/blob/master/SocialEvolution/Proximity.csv.bz2. It was initially skipped by github, because it was too big.
 It needs to be unzipped before using.
 A also uploaded the entire dataset to https://github.com/uoguelph-mlrg/LDG/blob/master/SocialEvolution.zip.

**Comment by bknyaz** [comment]
We couldn't reproduce their results unfortunately. Please see my comments about common issues of the DyRep paper here https://openreview.net/forum?id=HyePrhR5KX
If you find other issues with their paper/our implementation, please let us know.
To run the DyRep model using our code you just need to run: 
```python main.py```

However, this will use the filtered Proximity events by default. If you want to use the full dataset as in DyRep use flag `--prob 0`.
