### ISSUE TITLE
Pre-processed SocialEvolution dataset?

### ISSUE THREAD

**Issue by zhh0998** [uoguelph-mlrg/LDG#3]
Will the preprocessed version of the SocialEvolution dataset be publicly available？Why the GITHUB dataset provided is different from SocialEvolution？

**Comment by bknyaz** [comment]
The SocialEvolution and Github datasets are two different datasets available in respective folders. The original Github dataset is huge, so we provide a preprocessed version. SocialEvolution is small and a preprocessed version is prepared each time the training script is executed. 
All events for train/test splits of both datasets are stored in the `all_events` variable: https://github.com/uoguelph-mlrg/LDG/blob/master/social_data_loader.py#L101

`all_events` is a list of tuples: (node1, node2, type of event, timestamp)

So if you want to try other methods on these datasets, I would suggest saving `all_events` to .pkl file or something like that and loading them in your framework.
